[package]
name = "think_bitio"
version = "0.1.0"
authors = ["Matthew Collins <me@thinkof.name>"]
edition = "2018"

[features]

[dependencies]
byteorder = "1.3.1"
cgmath = { version = "0.17.0", optional = true }
